name: fusix
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0-326.0.dev

dependencies:
  dice_icons: ^0.1.7
  dynamic_color: ^1.7.0
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.14.1
  flutter_screenutil: ^5.9.3
  provider: ^6.1.2
  shared_preferences: ^2.3.2
  sizer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icon/