name: Debug

on:
  push:
    branches:
      - main  # Trigger on debug branch instead of main

jobs:
  build-win:
    runs-on: windows-latest

    steps:
      # Install Java 17 and set as JAVA_HOME
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '17'

      - uses: actions/checkout@v3

      - name: Test connection
        run: curl "https://storage.googleapis.com/flutter_infra_release/releases/releases_linux.json"

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.3'

      - name: Install dependencies
        run: flutter pub get

      - name: Build Windows
        run: flutter build windows --debug

      - name: Zip Windows Debug artifacts
        run: |
          cd build\windows\x64\runner\Debug
          powershell.exe -Command "Compress-Archive -Path Debug\* -DestinationPath windows_debug_artifacts.zip"

      # Archive the zipped artifacts
      - name: Archive Windows artifacts
        uses: actions/upload-artifact@v3
        with:
          name: windows-debug-artifacts
          path: build\windows\x64\runner\Debug\windows_debug_artifacts.zip  # Upload the zipped file

  build-apk-web:
    runs-on: ubuntu-latest

    steps:
      # Install Java 17 and set as JAVA_HOME
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '17'

      - uses: actions/checkout@v3

      - name: Test connection
        run: curl "https://storage.googleapis.com/flutter_infra_release/releases/releases_linux.json"

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.3'

      - name: Install dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --debug

      - name: Build Web
        run: flutter build web

      - name: Archive APK artifacts
        uses: actions/upload-artifact@v3
        with:
          name: debug-apk-artifacts
          path: build/app/outputs/flutter-apk/app-debug.apk  # Path to debug APK

      - name: Archive Web artifacts
        uses: actions/upload-artifact@v3
        with:
          name: debug-web-artifacts
          path: build/web/  # Path to built web artifacts
