name: Debug

on:
  push:
    branches:
      - main  # Trigger on debug branch instead of main

jobs:
  build-win:
    runs-on: windows-latest

    steps:
      # Install Java 17 and set as JAVA_HOME
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '17'

      - uses: actions/checkout@v3

      - name: Test connection
        run: curl "https://storage.googleapis.com/flutter_infra_release/releases/releases_linux.json"

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.3'

      - name: Install dependencies
        run: flutter pub get

      - name: Build Windows
        run: flutter build windows --debug

      - name: Zip Windows Debug artifacts
        run: |
          cd build\windows\x64\runner
          powershell.exe -Command "Compress-Archive -Path Debug\* -DestinationPath windows_debug_artifacts.zip"

      # Archive the zipped artifacts
      - name: Upload Windows artifacts
        uses: actions/upload-artifact@v3
        with:
          name: windows-debug.zip
          path: build\windows\x64\runner\windows_debug_artifacts.zip  # Upload the zipped file

  build-apk-web:
    runs-on: ubuntu-latest

    steps:
      # Install Java 17 and set as JAVA_HOME
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '17'

      - uses: actions/checkout@v3

      - name: Test connection
        run: curl "https://storage.googleapis.com/flutter_infra_release/releases/releases_linux.json"

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.3'

      - name: Install dependencies
        run: flutter pub get

      # Build normal APK
      - name: Build normal APK (single APK)
        run: flutter build apk --debug

      # Build APKs split by ABI
      - name: Build APK (split by ABI)
        run: flutter build apk --debug --split-per-abi

      - name: Build Web
        run: flutter build web

      # Upload normal APK directly (without archiving)
      - name: Upload normal APK
        uses: actions/upload-artifact@v3
        with:
          name: app-debug.apk
          path: build/app/outputs/flutter-apk/app-debug.apk  # Path to the normal APK

      # Upload split APKs for each ABI (without archiving)
      - name: Upload armeabi-v7a APK
        uses: actions/upload-artifact@v3
        with:
          name: app-armeabi-v7a-debug.apk
          path: build/app/outputs/flutter-apk/app-armeabi-v7a-debug.apk  # Path to the armeabi-v7a APK

      - name: Upload arm64-v8a APK
        uses: actions/upload-artifact@v3
        with:
          name: app-arm64-v8a-debug.apk
          path: build/app/outputs/flutter-apk/app-arm64-v8a-debug.apk  # Path to the arm64-v8a APK

      - name: Upload x86_64 APK
        uses: actions/upload-artifact@v3
        with:
          name: app-x86_64-debug.apk
          path: build/app/outputs/flutter-apk/app-x86_64-debug.apk

      - name: Archive Web artifacts
        uses: actions/upload-artifact@v3
        with:
          name: debug-web.zip
          path: build/web/  # Path to built web artifacts
